// This file has been autogenerated.

exports.scopes = [[],
[function (nock) { 
var result = 
nock('http://sdktestvault0511.vault.azure.net')
  .filteringRequestBody(function (path) { return '*';})
.put('/secrets/nodeSecret?api-version=2015-06-01', '*')
  .reply(401, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'www-authenticate': 'Bearer authorization="https://login.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47", resource="https://vault.azure.net"',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '67fdaf80-0d17-4b18-a548-c71d3af496c8',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:32 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://sdktestvault0511.vault.azure.net')
  .filteringRequestBody(function (path) { return '*';})
.put('/secrets/nodeSecret?api-version=2015-06-01', '*')
  .reply(401, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'www-authenticate': 'Bearer authorization="https://login.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47", resource="https://vault.azure.net"',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '67fdaf80-0d17-4b18-a548-c71d3af496c8',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:32 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://sdktestvault0511.vault.azure.net')
  .filteringRequestBody(function (path) { return '*';})
.put('/secrets/nodeSecret?api-version=2015-06-01', '*')
  .reply(200, "{\"value\":\"Pa$$w0rd\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeSecret/4ec56410b02d45ff97440a2c78f8e83e\",\"attributes\":{\"enabled\":true,\"created\":1470355113,\"updated\":1470355113}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '5bf46847-573d-4b29-a9f2-b4dd9fe877c5',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:33 GMT',
  connection: 'close',
  'content-length': '192' });
 return result; },
function (nock) { 
var result = 
nock('https://sdktestvault0511.vault.azure.net')
  .filteringRequestBody(function (path) { return '*';})
.put('/secrets/nodeSecret?api-version=2015-06-01', '*')
  .reply(200, "{\"value\":\"Pa$$w0rd\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeSecret/4ec56410b02d45ff97440a2c78f8e83e\",\"attributes\":{\"enabled\":true,\"created\":1470355113,\"updated\":1470355113}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '5bf46847-573d-4b29-a9f2-b4dd9fe877c5',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:33 GMT',
  connection: 'close',
  'content-length': '192' });
 return result; },
function (nock) { 
var result = 
nock('http://sdktestvault0511.vault.azure.net')
  .get('/secrets/nodeSecret/?api-version=2015-06-01')
  .reply(200, "{\"value\":\"Pa$$w0rd\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeSecret/4ec56410b02d45ff97440a2c78f8e83e\",\"attributes\":{\"enabled\":true,\"created\":1470355113,\"updated\":1470355113}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '31b55dfa-679c-4a39-9558-b7d20df99e41',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:33 GMT',
  connection: 'close',
  'content-length': '192' });
 return result; },
function (nock) { 
var result = 
nock('https://sdktestvault0511.vault.azure.net')
  .get('/secrets/nodeSecret/?api-version=2015-06-01')
  .reply(200, "{\"value\":\"Pa$$w0rd\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeSecret/4ec56410b02d45ff97440a2c78f8e83e\",\"attributes\":{\"enabled\":true,\"created\":1470355113,\"updated\":1470355113}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '31b55dfa-679c-4a39-9558-b7d20df99e41',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:33 GMT',
  connection: 'close',
  'content-length': '192' });
 return result; },
function (nock) { 
var result = 
nock('http://sdktestvault0511.vault.azure.net')
  .get('/secrets/nodeSecret/4ec56410b02d45ff97440a2c78f8e83e?api-version=2015-06-01')
  .reply(200, "{\"value\":\"Pa$$w0rd\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeSecret/4ec56410b02d45ff97440a2c78f8e83e\",\"attributes\":{\"enabled\":true,\"created\":1470355113,\"updated\":1470355113}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '6922d7d0-5665-4d74-9b98-c85fd54ce1e6',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:34 GMT',
  connection: 'close',
  'content-length': '192' });
 return result; },
function (nock) { 
var result = 
nock('https://sdktestvault0511.vault.azure.net')
  .get('/secrets/nodeSecret/4ec56410b02d45ff97440a2c78f8e83e?api-version=2015-06-01')
  .reply(200, "{\"value\":\"Pa$$w0rd\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeSecret/4ec56410b02d45ff97440a2c78f8e83e\",\"attributes\":{\"enabled\":true,\"created\":1470355113,\"updated\":1470355113}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '6922d7d0-5665-4d74-9b98-c85fd54ce1e6',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:34 GMT',
  connection: 'close',
  'content-length': '192' });
 return result; },
function (nock) { 
var result = 
nock('http://sdktestvault0511.vault.azure.net')
  .filteringRequestBody(function (path) { return '*';})
.patch('/secrets/nodeSecret/?api-version=2015-06-01', '*')
  .reply(200, "{\"contentType\":\"text/plain\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeSecret/4ec56410b02d45ff97440a2c78f8e83e\",\"attributes\":{\"enabled\":true,\"exp\":2527401600,\"created\":1470355113,\"updated\":1470355114},\"tags\":{\"foo\":\"ede2c2613ab96101ef90e0f93ed400417324724f8d0793cc46156eb21c83a50b2aa6d24fbbdce46d3a06ef47b671ba579248\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': 'bf051c31-d09c-4894-b384-d9616a3d46ca',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:34 GMT',
  connection: 'close',
  'content-length': '335' });
 return result; },
function (nock) { 
var result = 
nock('https://sdktestvault0511.vault.azure.net')
  .filteringRequestBody(function (path) { return '*';})
.patch('/secrets/nodeSecret/?api-version=2015-06-01', '*')
  .reply(200, "{\"contentType\":\"text/plain\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeSecret/4ec56410b02d45ff97440a2c78f8e83e\",\"attributes\":{\"enabled\":true,\"exp\":2527401600,\"created\":1470355113,\"updated\":1470355114},\"tags\":{\"foo\":\"ede2c2613ab96101ef90e0f93ed400417324724f8d0793cc46156eb21c83a50b2aa6d24fbbdce46d3a06ef47b671ba579248\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': 'bf051c31-d09c-4894-b384-d9616a3d46ca',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:34 GMT',
  connection: 'close',
  'content-length': '335' });
 return result; },
function (nock) { 
var result = 
nock('http://sdktestvault0511.vault.azure.net')
  .filteringRequestBody(function (path) { return '*';})
.patch('/secrets/nodeSecret/4ec56410b02d45ff97440a2c78f8e83e?api-version=2015-06-01', '*')
  .reply(200, "{\"contentType\":\"text/plain\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeSecret/4ec56410b02d45ff97440a2c78f8e83e\",\"attributes\":{\"enabled\":true,\"exp\":2527401600,\"created\":1470355113,\"updated\":1470355115},\"tags\":{\"foo\":\"1c2113c5908b1633b597923b338e697e6396c6b61dea3431fd058d6efb89d103d134e7d6c14ec3c37686dccf447009884afa\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': 'a7e704d1-5465-4698-9a59-49e6f1ab35c5',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:34 GMT',
  connection: 'close',
  'content-length': '335' });
 return result; },
function (nock) { 
var result = 
nock('https://sdktestvault0511.vault.azure.net')
  .filteringRequestBody(function (path) { return '*';})
.patch('/secrets/nodeSecret/4ec56410b02d45ff97440a2c78f8e83e?api-version=2015-06-01', '*')
  .reply(200, "{\"contentType\":\"text/plain\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeSecret/4ec56410b02d45ff97440a2c78f8e83e\",\"attributes\":{\"enabled\":true,\"exp\":2527401600,\"created\":1470355113,\"updated\":1470355115},\"tags\":{\"foo\":\"1c2113c5908b1633b597923b338e697e6396c6b61dea3431fd058d6efb89d103d134e7d6c14ec3c37686dccf447009884afa\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': 'a7e704d1-5465-4698-9a59-49e6f1ab35c5',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:34 GMT',
  connection: 'close',
  'content-length': '335' });
 return result; },
function (nock) { 
var result = 
nock('http://sdktestvault0511.vault.azure.net')
  .delete('/secrets/nodeSecret?api-version=2015-06-01')
  .reply(200, "{\"contentType\":\"text/plain\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeSecret/4ec56410b02d45ff97440a2c78f8e83e\",\"attributes\":{\"enabled\":true,\"exp\":2527401600,\"created\":1470355113,\"updated\":1470355115},\"tags\":{\"foo\":\"1c2113c5908b1633b597923b338e697e6396c6b61dea3431fd058d6efb89d103d134e7d6c14ec3c37686dccf447009884afa\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': 'a74c0c1d-0d2f-4bab-b35a-def60783374d',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:35 GMT',
  connection: 'close',
  'content-length': '335' });
 return result; },
function (nock) { 
var result = 
nock('https://sdktestvault0511.vault.azure.net')
  .delete('/secrets/nodeSecret?api-version=2015-06-01')
  .reply(200, "{\"contentType\":\"text/plain\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeSecret/4ec56410b02d45ff97440a2c78f8e83e\",\"attributes\":{\"enabled\":true,\"exp\":2527401600,\"created\":1470355113,\"updated\":1470355115},\"tags\":{\"foo\":\"1c2113c5908b1633b597923b338e697e6396c6b61dea3431fd058d6efb89d103d134e7d6c14ec3c37686dccf447009884afa\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': 'a74c0c1d-0d2f-4bab-b35a-def60783374d',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:35 GMT',
  connection: 'close',
  'content-length': '335' });
 return result; },
function (nock) { 
var result = 
nock('http://sdktestvault0511.vault.azure.net')
  .get('/secrets/nodeSecret/?api-version=2015-06-01')
  .reply(404, "{\"error\":{\"code\":\"SecretNotFound\",\"message\":\"Secret not found: nodeSecret\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '76',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '1a4d668a-9fa5-46d8-8845-0a836c572f95',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:35 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://sdktestvault0511.vault.azure.net')
  .get('/secrets/nodeSecret/?api-version=2015-06-01')
  .reply(404, "{\"error\":{\"code\":\"SecretNotFound\",\"message\":\"Secret not found: nodeSecret\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '76',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '1a4d668a-9fa5-46d8-8845-0a836c572f95',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:35 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://sdktestvault0511.vault.azure.net')
  .filteringRequestBody(function (path) { return '*';})
.put('/secrets/nodeSecret1?api-version=2015-06-01', '*')
  .reply(200, "{\"value\":\"Pa$$w0rd\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeSecret1/6edf1707e31f455caa9143fa39063122\",\"attributes\":{\"enabled\":true,\"created\":1470355117,\"updated\":1470355117}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '124b0d40-df4d-4157-b1ae-d83c43c8dbe0',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:36 GMT',
  connection: 'close',
  'content-length': '193' });
 return result; },
function (nock) { 
var result = 
nock('https://sdktestvault0511.vault.azure.net')
  .filteringRequestBody(function (path) { return '*';})
.put('/secrets/nodeSecret1?api-version=2015-06-01', '*')
  .reply(200, "{\"value\":\"Pa$$w0rd\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeSecret1/6edf1707e31f455caa9143fa39063122\",\"attributes\":{\"enabled\":true,\"created\":1470355117,\"updated\":1470355117}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '124b0d40-df4d-4157-b1ae-d83c43c8dbe0',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:36 GMT',
  connection: 'close',
  'content-length': '193' });
 return result; },
function (nock) { 
var result = 
nock('http://sdktestvault0511.vault.azure.net')
  .filteringRequestBody(function (path) { return '*';})
.put('/secrets/nodeSecret2?api-version=2015-06-01', '*')
  .reply(200, "{\"value\":\"Pa$$w0rd\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeSecret2/e1cc86944b2e4cb29f54e5ed1175513b\",\"attributes\":{\"enabled\":true,\"created\":1470355116,\"updated\":1470355116}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '06c06a65-375a-490f-a16f-61de25d61d07',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:36 GMT',
  connection: 'close',
  'content-length': '193' });
 return result; },
function (nock) { 
var result = 
nock('https://sdktestvault0511.vault.azure.net')
  .filteringRequestBody(function (path) { return '*';})
.put('/secrets/nodeSecret2?api-version=2015-06-01', '*')
  .reply(200, "{\"value\":\"Pa$$w0rd\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeSecret2/e1cc86944b2e4cb29f54e5ed1175513b\",\"attributes\":{\"enabled\":true,\"created\":1470355116,\"updated\":1470355116}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '06c06a65-375a-490f-a16f-61de25d61d07',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:36 GMT',
  connection: 'close',
  'content-length': '193' });
 return result; },
function (nock) { 
var result = 
nock('http://sdktestvault0511.vault.azure.net')
  .get('/secrets?maxresults=2&api-version=2015-06-01')
  .reply(200, "{\"value\":[{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/createManualEnrollmentJava4\",\"attributes\":{\"enabled\":true,\"nbf\":1469048531,\"exp\":1500585131,\"created\":1469049131,\"updated\":1469049131}},{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/createManualEnrollmentJava6\",\"attributes\":{\"enabled\":true,\"nbf\":1469567919,\"exp\":1501104519,\"created\":1469568520,\"updated\":1469568520}}],\"nextLink\":\"https://sdktestvault0511.vault.azure.net:443/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiExMDQhTURBd01ETTBJWE5sWTNKbGRDOURVa1ZCVkVWTlFVNVZRVXhGVGxKUFRFeE5SVTVVU2tGV1FUY2hNREF3TURJNElUazVPVGt0TVRJdE16RlVNak02TlRrNk5Ua3VPVGs1T1RrNU9Wb2giLCJUYXJnZXRMb2NhdGlvbiI6MH0&maxresults=2\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '57a8599c-c6b0-4e57-a631-e87b9f33a164',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:36 GMT',
  connection: 'close',
  'content-length': '778' });
 return result; },
function (nock) { 
var result = 
nock('https://sdktestvault0511.vault.azure.net')
  .get('/secrets?maxresults=2&api-version=2015-06-01')
  .reply(200, "{\"value\":[{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/createManualEnrollmentJava4\",\"attributes\":{\"enabled\":true,\"nbf\":1469048531,\"exp\":1500585131,\"created\":1469049131,\"updated\":1469049131}},{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/createManualEnrollmentJava6\",\"attributes\":{\"enabled\":true,\"nbf\":1469567919,\"exp\":1501104519,\"created\":1469568520,\"updated\":1469568520}}],\"nextLink\":\"https://sdktestvault0511.vault.azure.net:443/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiExMDQhTURBd01ETTBJWE5sWTNKbGRDOURVa1ZCVkVWTlFVNVZRVXhGVGxKUFRFeE5SVTVVU2tGV1FUY2hNREF3TURJNElUazVPVGt0TVRJdE16RlVNak02TlRrNk5Ua3VPVGs1T1RrNU9Wb2giLCJUYXJnZXRMb2NhdGlvbiI6MH0&maxresults=2\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '57a8599c-c6b0-4e57-a631-e87b9f33a164',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:36 GMT',
  connection: 'close',
  'content-length': '778' });
 return result; },
function (nock) { 
var result = 
nock('http://sdktestvault0511.vault.azure.net')
  .get('/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiExMDQhTURBd01ETTBJWE5sWTNKbGRDOURVa1ZCVkVWTlFVNVZRVXhGVGxKUFRFeE5SVTVVU2tGV1FUY2hNREF3TURJNElUazVPVGt0TVRJdE16RlVNak02TlRrNk5Ua3VPVGs1T1RrNU9Wb2giLCJUYXJnZXRMb2NhdGlvbiI6MH0&maxresults=2')
  .reply(401, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'www-authenticate': 'Bearer authorization="https://login.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47", resource="https://vault.azure.net"',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '4f3fe0dd-1c0c-4a37-9417-e8190055ab0a',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:37 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://sdktestvault0511.vault.azure.net')
  .get('/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiExMDQhTURBd01ETTBJWE5sWTNKbGRDOURVa1ZCVkVWTlFVNVZRVXhGVGxKUFRFeE5SVTVVU2tGV1FUY2hNREF3TURJNElUazVPVGt0TVRJdE16RlVNak02TlRrNk5Ua3VPVGs1T1RrNU9Wb2giLCJUYXJnZXRMb2NhdGlvbiI6MH0&maxresults=2')
  .reply(401, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'www-authenticate': 'Bearer authorization="https://login.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47", resource="https://vault.azure.net"',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '4f3fe0dd-1c0c-4a37-9417-e8190055ab0a',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:37 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://sdktestvault0511.vault.azure.net')
  .get('/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiExMDQhTURBd01ETTBJWE5sWTNKbGRDOURVa1ZCVkVWTlFVNVZRVXhGVGxKUFRFeE5SVTVVU2tGV1FUY2hNREF3TURJNElUazVPVGt0TVRJdE16RlVNak02TlRrNk5Ua3VPVGs1T1RrNU9Wb2giLCJUYXJnZXRMb2NhdGlvbiI6MH0&maxresults=2')
  .reply(200, "{\"value\":[{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/createManualEnrollmentJava7\",\"attributes\":{\"enabled\":true,\"nbf\":1469568292,\"exp\":1501104892,\"created\":1469568892,\"updated\":1469568892}},{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/createManualEnrollmentJava8\",\"attributes\":{\"enabled\":true,\"nbf\":1469569754,\"exp\":1501106354,\"created\":1469570354,\"updated\":1469570354}}],\"nextLink\":\"https://sdktestvault0511.vault.azure.net:443/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiExMDQhTURBd01ETTBJWE5sWTNKbGRDOURVa1ZCVkVWTlFVNVZRVXhGVGxKUFRFeE5SVTVVU2tGV1FUa2hNREF3TURJNElUazVPVGt0TVRJdE16RlVNak02TlRrNk5Ua3VPVGs1T1RrNU9Wb2giLCJUYXJnZXRMb2NhdGlvbiI6MH0&maxresults=2\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': 'b1f94a0f-c5ea-4e79-958b-12cd743b45d4',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:37 GMT',
  connection: 'close',
  'content-length': '778' });
 return result; },
function (nock) { 
var result = 
nock('https://sdktestvault0511.vault.azure.net')
  .get('/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiExMDQhTURBd01ETTBJWE5sWTNKbGRDOURVa1ZCVkVWTlFVNVZRVXhGVGxKUFRFeE5SVTVVU2tGV1FUY2hNREF3TURJNElUazVPVGt0TVRJdE16RlVNak02TlRrNk5Ua3VPVGs1T1RrNU9Wb2giLCJUYXJnZXRMb2NhdGlvbiI6MH0&maxresults=2')
  .reply(200, "{\"value\":[{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/createManualEnrollmentJava7\",\"attributes\":{\"enabled\":true,\"nbf\":1469568292,\"exp\":1501104892,\"created\":1469568892,\"updated\":1469568892}},{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/createManualEnrollmentJava8\",\"attributes\":{\"enabled\":true,\"nbf\":1469569754,\"exp\":1501106354,\"created\":1469570354,\"updated\":1469570354}}],\"nextLink\":\"https://sdktestvault0511.vault.azure.net:443/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiExMDQhTURBd01ETTBJWE5sWTNKbGRDOURVa1ZCVkVWTlFVNVZRVXhGVGxKUFRFeE5SVTVVU2tGV1FUa2hNREF3TURJNElUazVPVGt0TVRJdE16RlVNak02TlRrNk5Ua3VPVGs1T1RrNU9Wb2giLCJUYXJnZXRMb2NhdGlvbiI6MH0&maxresults=2\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': 'b1f94a0f-c5ea-4e79-958b-12cd743b45d4',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:37 GMT',
  connection: 'close',
  'content-length': '778' });
 return result; },
function (nock) { 
var result = 
nock('http://sdktestvault0511.vault.azure.net')
  .get('/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiExMDQhTURBd01ETTBJWE5sWTNKbGRDOURVa1ZCVkVWTlFVNVZRVXhGVGxKUFRFeE5SVTVVU2tGV1FUa2hNREF3TURJNElUazVPVGt0TVRJdE16RlVNak02TlRrNk5Ua3VPVGs1T1RrNU9Wb2giLCJUYXJnZXRMb2NhdGlvbiI6MH0&maxresults=2')
  .reply(200, "{\"value\":[{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/createManualEnrollmentJava9\",\"attributes\":{\"enabled\":true,\"nbf\":1469574262,\"exp\":1501110862,\"created\":1469574863,\"updated\":1469574863}},{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/importListCertificate1\",\"attributes\":{\"enabled\":true,\"nbf\":1430344421,\"exp\":2208988799,\"created\":1469573295,\"updated\":1469573295}}],\"nextLink\":\"https://sdktestvault0511.vault.azure.net:443/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiExMDAhTURBd01ESTVJWE5sWTNKbGRDOUpUVkJQVWxSTVNWTlVRMFZTVkVsR1NVTkJWRVV5SVRBd01EQXlPQ0U1T1RrNUxURXlMVE14VkRJek9qVTVPalU1TGprNU9UazVPVGxhSVEtLSIsIlRhcmdldExvY2F0aW9uIjowfQ&maxresults=2\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': 'a5ecabce-d83d-43d6-8941-fda5452ebc58',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:38 GMT',
  connection: 'close',
  'content-length': '768' });
 return result; },
function (nock) { 
var result = 
nock('https://sdktestvault0511.vault.azure.net')
  .get('/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiExMDQhTURBd01ETTBJWE5sWTNKbGRDOURVa1ZCVkVWTlFVNVZRVXhGVGxKUFRFeE5SVTVVU2tGV1FUa2hNREF3TURJNElUazVPVGt0TVRJdE16RlVNak02TlRrNk5Ua3VPVGs1T1RrNU9Wb2giLCJUYXJnZXRMb2NhdGlvbiI6MH0&maxresults=2')
  .reply(200, "{\"value\":[{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/createManualEnrollmentJava9\",\"attributes\":{\"enabled\":true,\"nbf\":1469574262,\"exp\":1501110862,\"created\":1469574863,\"updated\":1469574863}},{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/importListCertificate1\",\"attributes\":{\"enabled\":true,\"nbf\":1430344421,\"exp\":2208988799,\"created\":1469573295,\"updated\":1469573295}}],\"nextLink\":\"https://sdktestvault0511.vault.azure.net:443/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiExMDAhTURBd01ESTVJWE5sWTNKbGRDOUpUVkJQVWxSTVNWTlVRMFZTVkVsR1NVTkJWRVV5SVRBd01EQXlPQ0U1T1RrNUxURXlMVE14VkRJek9qVTVPalU1TGprNU9UazVPVGxhSVEtLSIsIlRhcmdldExvY2F0aW9uIjowfQ&maxresults=2\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': 'a5ecabce-d83d-43d6-8941-fda5452ebc58',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:38 GMT',
  connection: 'close',
  'content-length': '768' });
 return result; },
function (nock) { 
var result = 
nock('http://sdktestvault0511.vault.azure.net')
  .get('/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiExMDAhTURBd01ESTVJWE5sWTNKbGRDOUpUVkJQVWxSTVNWTlVRMFZTVkVsR1NVTkJWRVV5SVRBd01EQXlPQ0U1T1RrNUxURXlMVE14VkRJek9qVTVPalU1TGprNU9UazVPVGxhSVEtLSIsIlRhcmdldExvY2F0aW9uIjowfQ&maxresults=2')
  .reply(200, "{\"value\":[{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/importListCertificate2\",\"attributes\":{\"enabled\":true,\"nbf\":1430344421,\"exp\":2208988799,\"created\":1469573296,\"updated\":1469573296}},{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/importListVersionCerts\",\"attributes\":{\"enabled\":true,\"nbf\":1430344421,\"exp\":2208988799,\"created\":1469573304,\"updated\":1469573304}}],\"nextLink\":\"https://sdktestvault0511.vault.azure.net:443/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiE4NCFNREF3TURFM0lYTmxZM0psZEM5S1FWWkJVMFZEVWtWVUlUQXdNREF5T0NFeU1ERTJMVEE0TFRBelZESXdPalUzT2pBeUxqQTVOelV5TmpGYUlRLS0iLCJUYXJnZXRMb2NhdGlvbiI6MH0&maxresults=2\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '4b787736-a73e-41be-8abf-70cc7d99cc87',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:39 GMT',
  connection: 'close',
  'content-length': '740' });
 return result; },
function (nock) { 
var result = 
nock('https://sdktestvault0511.vault.azure.net')
  .get('/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiExMDAhTURBd01ESTVJWE5sWTNKbGRDOUpUVkJQVWxSTVNWTlVRMFZTVkVsR1NVTkJWRVV5SVRBd01EQXlPQ0U1T1RrNUxURXlMVE14VkRJek9qVTVPalU1TGprNU9UazVPVGxhSVEtLSIsIlRhcmdldExvY2F0aW9uIjowfQ&maxresults=2')
  .reply(200, "{\"value\":[{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/importListCertificate2\",\"attributes\":{\"enabled\":true,\"nbf\":1430344421,\"exp\":2208988799,\"created\":1469573296,\"updated\":1469573296}},{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/importListVersionCerts\",\"attributes\":{\"enabled\":true,\"nbf\":1430344421,\"exp\":2208988799,\"created\":1469573304,\"updated\":1469573304}}],\"nextLink\":\"https://sdktestvault0511.vault.azure.net:443/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiE4NCFNREF3TURFM0lYTmxZM0psZEM5S1FWWkJVMFZEVWtWVUlUQXdNREF5T0NFeU1ERTJMVEE0TFRBelZESXdPalUzT2pBeUxqQTVOelV5TmpGYUlRLS0iLCJUYXJnZXRMb2NhdGlvbiI6MH0&maxresults=2\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '4b787736-a73e-41be-8abf-70cc7d99cc87',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:39 GMT',
  connection: 'close',
  'content-length': '740' });
 return result; },
function (nock) { 
var result = 
nock('http://sdktestvault0511.vault.azure.net')
  .get('/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiE4NCFNREF3TURFM0lYTmxZM0psZEM5S1FWWkJVMFZEVWtWVUlUQXdNREF5T0NFeU1ERTJMVEE0TFRBelZESXdPalUzT2pBeUxqQTVOelV5TmpGYUlRLS0iLCJUYXJnZXRMb2NhdGlvbiI6MH0&maxresults=2')
  .reply(200, "{\"value\":[{\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/javaSecret\",\"attributes\":{\"enabled\":true,\"created\":1470257822,\"updated\":1470257822}},{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/listCertificate0\",\"attributes\":{\"enabled\":true,\"nbf\":1430344421,\"exp\":2208988799,\"created\":1470257498,\"updated\":1470257498}}],\"nextLink\":\"https://sdktestvault0511.vault.azure.net:443/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiE5MiFNREF3TURJeklYTmxZM0psZEM5TVNWTlVRMFZTVkVsR1NVTkJWRVV4SVRBd01EQXlPQ0U1T1RrNUxURXlMVE14VkRJek9qVTVPalU1TGprNU9UazVPVGxhSVEtLSIsIlRhcmdldExvY2F0aW9uIjowfQ&maxresults=2\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '3fe1cbcf-cdc8-4465-bddb-70a2890cb98b',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:38 GMT',
  connection: 'close',
  'content-length': '662' });
 return result; },
function (nock) { 
var result = 
nock('https://sdktestvault0511.vault.azure.net')
  .get('/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiE4NCFNREF3TURFM0lYTmxZM0psZEM5S1FWWkJVMFZEVWtWVUlUQXdNREF5T0NFeU1ERTJMVEE0TFRBelZESXdPalUzT2pBeUxqQTVOelV5TmpGYUlRLS0iLCJUYXJnZXRMb2NhdGlvbiI6MH0&maxresults=2')
  .reply(200, "{\"value\":[{\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/javaSecret\",\"attributes\":{\"enabled\":true,\"created\":1470257822,\"updated\":1470257822}},{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/listCertificate0\",\"attributes\":{\"enabled\":true,\"nbf\":1430344421,\"exp\":2208988799,\"created\":1470257498,\"updated\":1470257498}}],\"nextLink\":\"https://sdktestvault0511.vault.azure.net:443/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiE5MiFNREF3TURJeklYTmxZM0psZEM5TVNWTlVRMFZTVkVsR1NVTkJWRVV4SVRBd01EQXlPQ0U1T1RrNUxURXlMVE14VkRJek9qVTVPalU1TGprNU9UazVPVGxhSVEtLSIsIlRhcmdldExvY2F0aW9uIjowfQ&maxresults=2\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '3fe1cbcf-cdc8-4465-bddb-70a2890cb98b',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:38 GMT',
  connection: 'close',
  'content-length': '662' });
 return result; },
function (nock) { 
var result = 
nock('http://sdktestvault0511.vault.azure.net')
  .get('/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiE5MiFNREF3TURJeklYTmxZM0psZEM5TVNWTlVRMFZTVkVsR1NVTkJWRVV4SVRBd01EQXlPQ0U1T1RrNUxURXlMVE14VkRJek9qVTVPalU1TGprNU9UazVPVGxhSVEtLSIsIlRhcmdldExvY2F0aW9uIjowfQ&maxresults=2')
  .reply(200, "{\"value\":[{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/listCertificate1\",\"attributes\":{\"enabled\":true,\"nbf\":1430344421,\"exp\":2208988799,\"created\":1470257501,\"updated\":1470257501}},{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/listCertificate2\",\"attributes\":{\"enabled\":true,\"nbf\":1430344421,\"exp\":2208988799,\"created\":1470257503,\"updated\":1470257503}}],\"nextLink\":\"https://sdktestvault0511.vault.azure.net:443/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiE5MiFNREF3TURJeklYTmxZM0psZEM5TVNWTlVRMFZTVkVsR1NVTkJWRVV6SVRBd01EQXlPQ0U1T1RrNUxURXlMVE14VkRJek9qVTVPalU1TGprNU9UazVPVGxhSVEtLSIsIlRhcmdldExvY2F0aW9uIjowfQ&maxresults=2\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '6d0c3d5f-266f-4ded-84f9-cf2493272879',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:39 GMT',
  connection: 'close',
  'content-length': '739' });
 return result; },
function (nock) { 
var result = 
nock('https://sdktestvault0511.vault.azure.net')
  .get('/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiE5MiFNREF3TURJeklYTmxZM0psZEM5TVNWTlVRMFZTVkVsR1NVTkJWRVV4SVRBd01EQXlPQ0U1T1RrNUxURXlMVE14VkRJek9qVTVPalU1TGprNU9UazVPVGxhSVEtLSIsIlRhcmdldExvY2F0aW9uIjowfQ&maxresults=2')
  .reply(200, "{\"value\":[{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/listCertificate1\",\"attributes\":{\"enabled\":true,\"nbf\":1430344421,\"exp\":2208988799,\"created\":1470257501,\"updated\":1470257501}},{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/listCertificate2\",\"attributes\":{\"enabled\":true,\"nbf\":1430344421,\"exp\":2208988799,\"created\":1470257503,\"updated\":1470257503}}],\"nextLink\":\"https://sdktestvault0511.vault.azure.net:443/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiE5MiFNREF3TURJeklYTmxZM0psZEM5TVNWTlVRMFZTVkVsR1NVTkJWRVV6SVRBd01EQXlPQ0U1T1RrNUxURXlMVE14VkRJek9qVTVPalU1TGprNU9UazVPVGxhSVEtLSIsIlRhcmdldExvY2F0aW9uIjowfQ&maxresults=2\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '6d0c3d5f-266f-4ded-84f9-cf2493272879',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:39 GMT',
  connection: 'close',
  'content-length': '739' });
 return result; },
function (nock) { 
var result = 
nock('http://sdktestvault0511.vault.azure.net')
  .get('/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiE5MiFNREF3TURJeklYTmxZM0psZEM5TVNWTlVRMFZTVkVsR1NVTkJWRVV6SVRBd01EQXlPQ0U1T1RrNUxURXlMVE14VkRJek9qVTVPalU1TGprNU9UazVPVGxhSVEtLSIsIlRhcmdldExvY2F0aW9uIjowfQ&maxresults=2')
  .reply(200, "{\"value\":[{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/listCertificate3\",\"attributes\":{\"enabled\":true,\"nbf\":1430344421,\"exp\":2208988799,\"created\":1470257505,\"updated\":1470257505}},{\"contentType\":\"test secret\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/mysecret\",\"attributes\":{\"enabled\":true,\"nbf\":1451635200,\"exp\":2527401600,\"created\":1470349692,\"updated\":1470349692}}],\"nextLink\":\"https://sdktestvault0511.vault.azure.net:443/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiE5NiFNREF3TURJNElYTmxZM0psZEM5T1QwUkZTVTFRVDFKVVEwVlNWRWxHU1VOQlZFVWhNREF3TURJNElUazVPVGt0TVRJdE16RlVNak02TlRrNk5Ua3VPVGs1T1RrNU9Wb2giLCJUYXJnZXRMb2NhdGlvbiI6MH0&maxresults=2\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '9529bf90-d388-49a0-99cd-2ad20759817c',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:40 GMT',
  connection: 'close',
  'content-length': '727' });
 return result; },
function (nock) { 
var result = 
nock('https://sdktestvault0511.vault.azure.net')
  .get('/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiE5MiFNREF3TURJeklYTmxZM0psZEM5TVNWTlVRMFZTVkVsR1NVTkJWRVV6SVRBd01EQXlPQ0U1T1RrNUxURXlMVE14VkRJek9qVTVPalU1TGprNU9UazVPVGxhSVEtLSIsIlRhcmdldExvY2F0aW9uIjowfQ&maxresults=2')
  .reply(200, "{\"value\":[{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/listCertificate3\",\"attributes\":{\"enabled\":true,\"nbf\":1430344421,\"exp\":2208988799,\"created\":1470257505,\"updated\":1470257505}},{\"contentType\":\"test secret\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/mysecret\",\"attributes\":{\"enabled\":true,\"nbf\":1451635200,\"exp\":2527401600,\"created\":1470349692,\"updated\":1470349692}}],\"nextLink\":\"https://sdktestvault0511.vault.azure.net:443/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiE5NiFNREF3TURJNElYTmxZM0psZEM5T1QwUkZTVTFRVDFKVVEwVlNWRWxHU1VOQlZFVWhNREF3TURJNElUazVPVGt0TVRJdE16RlVNak02TlRrNk5Ua3VPVGs1T1RrNU9Wb2giLCJUYXJnZXRMb2NhdGlvbiI6MH0&maxresults=2\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '9529bf90-d388-49a0-99cd-2ad20759817c',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:40 GMT',
  connection: 'close',
  'content-length': '727' });
 return result; },
function (nock) { 
var result = 
nock('http://sdktestvault0511.vault.azure.net')
  .get('/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiE5NiFNREF3TURJNElYTmxZM0psZEM5T1QwUkZTVTFRVDFKVVEwVlNWRWxHU1VOQlZFVWhNREF3TURJNElUazVPVGt0TVRJdE16RlVNak02TlRrNk5Ua3VPVGs1T1RrNU9Wb2giLCJUYXJnZXRMb2NhdGlvbiI6MH0&maxresults=2')
  .reply(200, "{\"value\":[{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeImportCertificate\",\"attributes\":{\"enabled\":true,\"nbf\":1430344421,\"exp\":2208988799,\"created\":1469573293,\"updated\":1469573293}},{\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeSecret1\",\"attributes\":{\"enabled\":true,\"created\":1470355117,\"updated\":1470355117}}],\"nextLink\":\"https://sdktestvault0511.vault.azure.net:443/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiE4NCFNREF3TURFNElYTmxZM0psZEM5T1QwUkZVMFZEVWtWVU1pRXdNREF3TWpnaE9UazVPUzB4TWkwek1WUXlNem8xT1RvMU9TNDVPVGs1T1RrNVdpRS0iLCJUYXJnZXRMb2NhdGlvbiI6MH0&maxresults=2\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '99fe4c1a-7a0b-415f-a5dd-4dec10f541cc',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:41 GMT',
  connection: 'close',
  'content-length': '657' });
 return result; },
function (nock) { 
var result = 
nock('https://sdktestvault0511.vault.azure.net')
  .get('/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiE5NiFNREF3TURJNElYTmxZM0psZEM5T1QwUkZTVTFRVDFKVVEwVlNWRWxHU1VOQlZFVWhNREF3TURJNElUazVPVGt0TVRJdE16RlVNak02TlRrNk5Ua3VPVGs1T1RrNU9Wb2giLCJUYXJnZXRMb2NhdGlvbiI6MH0&maxresults=2')
  .reply(200, "{\"value\":[{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeImportCertificate\",\"attributes\":{\"enabled\":true,\"nbf\":1430344421,\"exp\":2208988799,\"created\":1469573293,\"updated\":1469573293}},{\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeSecret1\",\"attributes\":{\"enabled\":true,\"created\":1470355117,\"updated\":1470355117}}],\"nextLink\":\"https://sdktestvault0511.vault.azure.net:443/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiE4NCFNREF3TURFNElYTmxZM0psZEM5T1QwUkZVMFZEVWtWVU1pRXdNREF3TWpnaE9UazVPUzB4TWkwek1WUXlNem8xT1RvMU9TNDVPVGs1T1RrNVdpRS0iLCJUYXJnZXRMb2NhdGlvbiI6MH0&maxresults=2\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '99fe4c1a-7a0b-415f-a5dd-4dec10f541cc',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:41 GMT',
  connection: 'close',
  'content-length': '657' });
 return result; },
function (nock) { 
var result = 
nock('http://sdktestvault0511.vault.azure.net')
  .get('/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiE4NCFNREF3TURFNElYTmxZM0psZEM5T1QwUkZVMFZEVWtWVU1pRXdNREF3TWpnaE9UazVPUzB4TWkwek1WUXlNem8xT1RvMU9TNDVPVGs1T1RrNVdpRS0iLCJUYXJnZXRMb2NhdGlvbiI6MH0&maxresults=2')
  .reply(200, "{\"value\":[{\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeSecret2\",\"attributes\":{\"enabled\":true,\"created\":1470355116,\"updated\":1470355116}},{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/policyCertificate\",\"attributes\":{\"enabled\":true,\"nbf\":1430344421,\"exp\":2208988799,\"created\":1469573312,\"updated\":1469573312}}],\"nextLink\":\"https://sdktestvault0511.vault.azure.net:443/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiE3NiFNREF3TURFeElYTmxZM0psZEM5VFJVTXhJVEF3TURBeU9DRTVPVGs1TFRFeUxUTXhWREl6T2pVNU9qVTVMams1T1RrNU9UbGFJUS0tIiwiVGFyZ2V0TG9jYXRpb24iOjB9&maxresults=2\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '7ceec6e0-9ce0-4f71-b629-8f90e6e2bd6d',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:41 GMT',
  connection: 'close',
  'content-length': '642' });
 return result; },
function (nock) { 
var result = 
nock('https://sdktestvault0511.vault.azure.net')
  .get('/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiE4NCFNREF3TURFNElYTmxZM0psZEM5T1QwUkZVMFZEVWtWVU1pRXdNREF3TWpnaE9UazVPUzB4TWkwek1WUXlNem8xT1RvMU9TNDVPVGs1T1RrNVdpRS0iLCJUYXJnZXRMb2NhdGlvbiI6MH0&maxresults=2')
  .reply(200, "{\"value\":[{\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeSecret2\",\"attributes\":{\"enabled\":true,\"created\":1470355116,\"updated\":1470355116}},{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/policyCertificate\",\"attributes\":{\"enabled\":true,\"nbf\":1430344421,\"exp\":2208988799,\"created\":1469573312,\"updated\":1469573312}}],\"nextLink\":\"https://sdktestvault0511.vault.azure.net:443/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiE3NiFNREF3TURFeElYTmxZM0psZEM5VFJVTXhJVEF3TURBeU9DRTVPVGs1TFRFeUxUTXhWREl6T2pVNU9qVTVMams1T1RrNU9UbGFJUS0tIiwiVGFyZ2V0TG9jYXRpb24iOjB9&maxresults=2\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '7ceec6e0-9ce0-4f71-b629-8f90e6e2bd6d',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:41 GMT',
  connection: 'close',
  'content-length': '642' });
 return result; },
function (nock) { 
var result = 
nock('http://sdktestvault0511.vault.azure.net')
  .get('/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiE3NiFNREF3TURFeElYTmxZM0psZEM5VFJVTXhJVEF3TURBeU9DRTVPVGs1TFRFeUxUTXhWREl6T2pVNU9qVTVMams1T1RrNU9UbGFJUS0tIiwiVGFyZ2V0TG9jYXRpb24iOjB9&maxresults=2')
  .reply(200, "{\"value\":[{\"contentType\":\"test secret\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/sec1\",\"attributes\":{\"enabled\":true,\"nbf\":1451635200,\"exp\":2527401600,\"created\":1470348580,\"updated\":1470348580}},{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/UnknownIssuerCert\",\"attributes\":{\"enabled\":true,\"nbf\":1469493191,\"exp\":1501029791,\"created\":1469493792,\"updated\":1469493792}}],\"nextLink\":null}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': 'edbfa80e-8918-4680-a041-7c6925af496b',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:40 GMT',
  connection: 'close',
  'content-length': '443' });
 return result; },
function (nock) { 
var result = 
nock('https://sdktestvault0511.vault.azure.net')
  .get('/secrets?api-version=2015-06-01&$skiptoken=eyJOZXh0TWFya2VyIjoiMiE3NiFNREF3TURFeElYTmxZM0psZEM5VFJVTXhJVEF3TURBeU9DRTVPVGs1TFRFeUxUTXhWREl6T2pVNU9qVTVMams1T1RrNU9UbGFJUS0tIiwiVGFyZ2V0TG9jYXRpb24iOjB9&maxresults=2')
  .reply(200, "{\"value\":[{\"contentType\":\"test secret\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/sec1\",\"attributes\":{\"enabled\":true,\"nbf\":1451635200,\"exp\":2527401600,\"created\":1470348580,\"updated\":1470348580}},{\"contentType\":\"application/x-pkcs12\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/UnknownIssuerCert\",\"attributes\":{\"enabled\":true,\"nbf\":1469493191,\"exp\":1501029791,\"created\":1469493792,\"updated\":1469493792}}],\"nextLink\":null}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': 'edbfa80e-8918-4680-a041-7c6925af496b',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:40 GMT',
  connection: 'close',
  'content-length': '443' });
 return result; }],
[function (nock) { 
var result = 
nock('http://sdktestvault0511.vault.azure.net')
  .filteringRequestBody(function (path) { return '*';})
.put('/secrets/nodeSecret?api-version=2015-06-01', '*')
  .reply(200, "{\"value\":\"Pa$$w0rd\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeSecret/6b622c80c2f84b80b9f2b955cdd3615e\",\"attributes\":{\"enabled\":true,\"created\":1470355122,\"updated\":1470355122}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '9bbb829c-4206-4cd7-8106-428bdad487a1',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:42 GMT',
  connection: 'close',
  'content-length': '192' });
 return result; },
function (nock) { 
var result = 
nock('https://sdktestvault0511.vault.azure.net')
  .filteringRequestBody(function (path) { return '*';})
.put('/secrets/nodeSecret?api-version=2015-06-01', '*')
  .reply(200, "{\"value\":\"Pa$$w0rd\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeSecret/6b622c80c2f84b80b9f2b955cdd3615e\",\"attributes\":{\"enabled\":true,\"created\":1470355122,\"updated\":1470355122}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '9bbb829c-4206-4cd7-8106-428bdad487a1',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:42 GMT',
  connection: 'close',
  'content-length': '192' });
 return result; },
function (nock) { 
var result = 
nock('http://sdktestvault0511.vault.azure.net')
  .filteringRequestBody(function (path) { return '*';})
.put('/secrets/nodeSecret?api-version=2015-06-01', '*')
  .reply(200, "{\"value\":\"Pa$$w0rd\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeSecret/48729358800f4d4b85cdb1442f5586c6\",\"attributes\":{\"enabled\":true,\"created\":1470355123,\"updated\":1470355123}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '60098dc7-1ac9-4147-808a-382892714aa2',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:43 GMT',
  connection: 'close',
  'content-length': '192' });
 return result; },
function (nock) { 
var result = 
nock('https://sdktestvault0511.vault.azure.net')
  .filteringRequestBody(function (path) { return '*';})
.put('/secrets/nodeSecret?api-version=2015-06-01', '*')
  .reply(200, "{\"value\":\"Pa$$w0rd\",\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeSecret/48729358800f4d4b85cdb1442f5586c6\",\"attributes\":{\"enabled\":true,\"created\":1470355123,\"updated\":1470355123}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '60098dc7-1ac9-4147-808a-382892714aa2',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:43 GMT',
  connection: 'close',
  'content-length': '192' });
 return result; },
function (nock) { 
var result = 
nock('http://sdktestvault0511.vault.azure.net')
  .get('/secrets/nodeSecret/versions?api-version=2015-06-01')
  .reply(200, "{\"value\":[{\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeSecret/48729358800f4d4b85cdb1442f5586c6\",\"attributes\":{\"enabled\":true,\"created\":1470355123,\"updated\":1470355123}},{\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeSecret/6b622c80c2f84b80b9f2b955cdd3615e\",\"attributes\":{\"enabled\":true,\"created\":1470355122,\"updated\":1470355122}}],\"nextLink\":null}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '905c9eff-b8b5-4e27-b9d5-3d2f48e7f4a7',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:42 GMT',
  connection: 'close',
  'content-length': '375' });
 return result; },
function (nock) { 
var result = 
nock('https://sdktestvault0511.vault.azure.net')
  .get('/secrets/nodeSecret/versions?api-version=2015-06-01')
  .reply(200, "{\"value\":[{\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeSecret/48729358800f4d4b85cdb1442f5586c6\",\"attributes\":{\"enabled\":true,\"created\":1470355123,\"updated\":1470355123}},{\"id\":\"https://sdktestvault0511.vault.azure.net/secrets/nodeSecret/6b622c80c2f84b80b9f2b955cdd3615e\",\"attributes\":{\"enabled\":true,\"created\":1470355122,\"updated\":1470355122}}],\"nextLink\":null}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-keyvault-region': 'East US',
  'x-ms-request-id': '905c9eff-b8b5-4e27-b9d5-3d2f48e7f4a7',
  'x-ms-keyvault-service-version': '1.0.0.763',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'strict-transport-security': 'max-age=31536000;includeSubDomains',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 04 Aug 2016 23:58:42 GMT',
  connection: 'close',
  'content-length': '375' });
 return result; }]];