/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the Action class.
 * @constructor
 * @member {string} [actionType] The type of the action.
 * 
 */
function Action() {
}

/**
 * Defines the metadata of Action
 *
 * @returns {object} metadata of Action
 *
 */
Action.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'Action',
    type: {
      name: 'Composite',
      className: 'Action',
      modelProperties: {
        actionType: {
          required: false,
          serializedName: 'action_type',
          type: {
            name: 'String'
          }
        }
      }
    }
  };
};

module.exports = Action;
