/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

var util = require('util');

/**
 * @class
 * Initializes a new instance of the CertificateIssuerListResult class.
 * @constructor
 * @member {array} [value] A response message containing a list of certificate
 * issuers in the vault along with a link to the next page of certificate
 * issuers
 * 
 */
function CertificateIssuerListResult() {
}

util.inherits(CertificateIssuerListResult, Array);

/**
 * Defines the metadata of CertificateIssuerListResult
 *
 * @returns {object} metadata of CertificateIssuerListResult
 *
 */
CertificateIssuerListResult.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'CertificateIssuerListResult',
    type: {
      name: 'Composite',
      className: 'CertificateIssuerListResult',
      modelProperties: {
        value: {
          required: false,
          readOnly: true,
          serializedName: '',
          type: {
            name: 'Sequence',
            element: {
                required: false,
                serializedName: 'CertificateIssuerItemElementType',
                type: {
                  name: 'Composite',
                  className: 'CertificateIssuerItem'
                }
            }
          }
        }
      }
    }
  };
};

module.exports = CertificateIssuerListResult;
