/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the IssuerReference class.
 * @constructor
 * @member {string} [name] Name of the referenced issuer object.
 * 
 */
function IssuerReference() {
}

/**
 * Defines the metadata of IssuerReference
 *
 * @returns {object} metadata of IssuerReference
 *
 */
IssuerReference.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'IssuerReference',
    type: {
      name: 'Composite',
      className: 'IssuerReference',
      modelProperties: {
        name: {
          required: false,
          serializedName: 'name',
          type: {
            name: 'String'
          }
        }
      }
    }
  };
};

module.exports = IssuerReference;
