/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

var util = require('util');

/**
 * @class
 * Initializes a new instance of the JsonWebKey class.
 * @constructor
 * @member {string} [kid] Key Identifier
 * 
 * @member {string} [kty] Key type, usually RSA
 * 
 * @member {array} [keyOps]
 * 
 * @member {buffer} [n] RSA modulus
 * 
 * @member {buffer} [e] RSA public exponent
 * 
 * @member {buffer} [d] RSA private exponent
 * 
 * @member {buffer} [dp]
 * 
 * @member {buffer} [dq]
 * 
 * @member {buffer} [qi]
 * 
 * @member {buffer} [p]
 * 
 * @member {buffer} [q]
 * 
 * @member {buffer} [k] Symmetric key
 * 
 * @member {buffer} [t] HSM Token, used with Bring Your Own Key
 * 
 */
function JsonWebKey() {
}

/**
 * Defines the metadata of JsonWebKey
 *
 * @returns {object} metadata of JsonWebKey
 *
 */
JsonWebKey.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'JsonWebKey',
    type: {
      name: 'Composite',
      className: 'JsonWebKey',
      modelProperties: {
        kid: {
          required: false,
          serializedName: 'kid',
          type: {
            name: 'String'
          }
        },
        kty: {
          required: false,
          serializedName: 'kty',
          type: {
            name: 'String'
          }
        },
        keyOps: {
          required: false,
          serializedName: 'key_ops',
          type: {
            name: 'Sequence',
            element: {
                required: false,
                serializedName: 'StringElementType',
                type: {
                  name: 'String'
                }
            }
          }
        },
        n: {
          required: false,
          serializedName: 'n',
          type: {
            name: 'Base64Url'
          }
        },
        e: {
          required: false,
          serializedName: 'e',
          type: {
            name: 'Base64Url'
          }
        },
        d: {
          required: false,
          serializedName: 'd',
          type: {
            name: 'Base64Url'
          }
        },
        dp: {
          required: false,
          serializedName: 'dp',
          type: {
            name: 'Base64Url'
          }
        },
        dq: {
          required: false,
          serializedName: 'dq',
          type: {
            name: 'Base64Url'
          }
        },
        qi: {
          required: false,
          serializedName: 'qi',
          type: {
            name: 'Base64Url'
          }
        },
        p: {
          required: false,
          serializedName: 'p',
          type: {
            name: 'Base64Url'
          }
        },
        q: {
          required: false,
          serializedName: 'q',
          type: {
            name: 'Base64Url'
          }
        },
        k: {
          required: false,
          serializedName: 'K',
          type: {
            name: 'Base64Url'
          }
        },
        t: {
          required: false,
          serializedName: 'key_hsm',
          type: {
            name: 'Base64Url'
          }
        }
      }
    }
  };
};

module.exports = JsonWebKey;
