/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

var util = require('util');

/**
 * @class
 * Initializes a new instance of the KeyListResult class.
 * @constructor
 * @member {array} [value] A response message containing a list of secrets in
 * the vault along with a link to the next page of secrets
 * 
 */
function KeyListResult() {
}

util.inherits(KeyListResult, Array);

/**
 * Defines the metadata of KeyListResult
 *
 * @returns {object} metadata of KeyListResult
 *
 */
KeyListResult.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'KeyListResult',
    type: {
      name: 'Composite',
      className: 'KeyListResult',
      modelProperties: {
        value: {
          required: false,
          readOnly: true,
          serializedName: '',
          type: {
            name: 'Sequence',
            element: {
                required: false,
                serializedName: 'KeyItemElementType',
                type: {
                  name: 'Composite',
                  className: 'KeyItem'
                }
            }
          }
        }
      }
    }
  };
};

module.exports = KeyListResult;
