/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the KeyRestoreParameters class.
 * @constructor
 * @member {buffer} keyBundleBackup the backup blob associated with a key
 * bundle
 * 
 */
function KeyRestoreParameters() {
}

/**
 * Defines the metadata of KeyRestoreParameters
 *
 * @returns {object} metadata of KeyRestoreParameters
 *
 */
KeyRestoreParameters.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'KeyRestoreParameters',
    type: {
      name: 'Composite',
      className: 'KeyRestoreParameters',
      modelProperties: {
        keyBundleBackup: {
          required: true,
          serializedName: 'value',
          type: {
            name: 'Base64Url'
          }
        }
      }
    }
  };
};

module.exports = KeyRestoreParameters;
