/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the KeyVaultError class.
 * @constructor
 * @member {string} [code]
 * 
 * @member {string} [message]
 * 
 * @member {object} [additionalInfo]
 * 
 */
function KeyVaultError() {
}

/**
 * Defines the metadata of KeyVaultError
 *
 * @returns {object} metadata of KeyVaultError
 *
 */
KeyVaultError.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'KeyVaultError',
    type: {
      name: 'Composite',
      className: 'KeyVaultError',
      modelProperties: {
        code: {
          required: false,
          readOnly: true,
          serializedName: 'error\\.code',
          type: {
            name: 'String'
          }
        },
        message: {
          required: false,
          readOnly: true,
          serializedName: 'error\\.message',
          type: {
            name: 'String'
          }
        },
        additionalInfo: {
          required: false,
          readOnly: true,
          serializedName: 'additionalInfo',
          type: {
            name: 'Object'
          }
        }
      }
    }
  };
};

module.exports = KeyVaultError;
