/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

var models = require('./index');

/**
 * @class
 * Initializes a new instance of the LifetimeAction class.
 * @constructor
 * @member {object} [trigger] The condition that will execute the action.
 * 
 * @member {number} [trigger.lifetimePercentage] The type of the action.
 * 
 * @member {object} [action] The action that will be executed.
 * 
 * @member {string} [action.actionType] The type of the action.
 * 
 */
function LifetimeAction() {
}

/**
 * Defines the metadata of LifetimeAction
 *
 * @returns {object} metadata of LifetimeAction
 *
 */
LifetimeAction.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'LifetimeAction',
    type: {
      name: 'Composite',
      className: 'LifetimeAction',
      modelProperties: {
        trigger: {
          required: false,
          serializedName: 'trigger',
          type: {
            name: 'Composite',
            className: 'Trigger'
          }
        },
        action: {
          required: false,
          serializedName: 'action',
          type: {
            name: 'Composite',
            className: 'Action'
          }
        }
      }
    }
  };
};

module.exports = LifetimeAction;
