/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

var models = require('./index');

var util = require('util');

/**
 * @class
 * Initializes a new instance of the OrganizationDetails class.
 * @constructor
 * @member {string} [name] Name of the organization.
 * 
 * @member {string} [address1] Address line 1.
 * 
 * @member {string} [address2] Address line 2.
 * 
 * @member {string} [city] City.
 * 
 * @member {string} [zipcode] Zipcode.
 * 
 * @member {string} [state] State.
 * 
 * @member {string} [country] Country.
 * 
 * @member {array} [administratorDetails] Details of the organization
 * administrator.
 * 
 */
function OrganizationDetails() {
}

/**
 * Defines the metadata of OrganizationDetails
 *
 * @returns {object} metadata of OrganizationDetails
 *
 */
OrganizationDetails.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'OrganizationDetails',
    type: {
      name: 'Composite',
      className: 'OrganizationDetails',
      modelProperties: {
        name: {
          required: false,
          serializedName: 'name',
          type: {
            name: 'String'
          }
        },
        address1: {
          required: false,
          serializedName: 'address1',
          type: {
            name: 'String'
          }
        },
        address2: {
          required: false,
          serializedName: 'address2',
          type: {
            name: 'String'
          }
        },
        city: {
          required: false,
          serializedName: 'city',
          type: {
            name: 'String'
          }
        },
        zipcode: {
          required: false,
          serializedName: 'zip',
          type: {
            name: 'String'
          }
        },
        state: {
          required: false,
          serializedName: 'state',
          type: {
            name: 'String'
          }
        },
        country: {
          required: false,
          serializedName: 'country',
          type: {
            name: 'String'
          }
        },
        administratorDetails: {
          required: false,
          serializedName: 'AdministratorDetails',
          type: {
            name: 'Sequence',
            element: {
                required: false,
                serializedName: 'AdministratorDetailsElementType',
                type: {
                  name: 'Composite',
                  className: 'AdministratorDetails'
                }
            }
          }
        }
      }
    }
  };
};

module.exports = OrganizationDetails;
