/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the PendingCertificateSigningRequestResult class.
 * @constructor
 * @member {string} [value] The pending certificate signing request as Base64
 * encoded string.
 * 
 */
function PendingCertificateSigningRequestResult() {
}

/**
 * Defines the metadata of PendingCertificateSigningRequestResult
 *
 * @returns {object} metadata of PendingCertificateSigningRequestResult
 *
 */
PendingCertificateSigningRequestResult.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'PendingCertificateSigningRequestResult',
    type: {
      name: 'Composite',
      className: 'PendingCertificateSigningRequestResult',
      modelProperties: {
        value: {
          required: false,
          readOnly: true,
          serializedName: 'value',
          type: {
            name: 'String'
          }
        }
      }
    }
  };
};

module.exports = PendingCertificateSigningRequestResult;
