/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the Trigger class.
 * @constructor
 * @member {number} [lifetimePercentage] The type of the action.
 * 
 */
function Trigger() {
}

/**
 * Defines the metadata of Trigger
 *
 * @returns {object} metadata of Trigger
 *
 */
Trigger.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'Trigger',
    type: {
      name: 'Composite',
      className: 'Trigger',
      modelProperties: {
        lifetimePercentage: {
          required: false,
          serializedName: 'lifetime_percentage',
          type: {
            name: 'Number'
          }
        }
      }
    }
  };
};

module.exports = Trigger;
