/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

var models = require('./index');

/**
 * @class
 * Initializes a new instance of the AccessPolicyEntry class.
 * @constructor
 * @member {uuid} [tenantId] Tenant ID of the principal
 * 
 * @member {uuid} [objectId] Object ID of the principal
 * 
 * @member {uuid} [applicationId]  Application ID of the client making request
 * on behalf of a principal
 * 
 * @member {object} [permissions] Permissions that the principal has for this
 * vault
 * 
 * @member {array} [permissions.keys] SKU family name
 * 
 * @member {array} [permissions.secrets] SKU name
 * 
 */
function AccessPolicyEntry() {
}

/**
 * Defines the metadata of AccessPolicyEntry
 *
 * @returns {object} metadata of AccessPolicyEntry
 *
 */
AccessPolicyEntry.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'AccessPolicyEntry',
    type: {
      name: 'Composite',
      className: 'AccessPolicyEntry',
      modelProperties: {
        tenantId: {
          required: false,
          serializedName: 'tenantId',
          type: {
            name: 'String'
          }
        },
        objectId: {
          required: false,
          serializedName: 'objectId',
          type: {
            name: 'String'
          }
        },
        applicationId: {
          required: false,
          serializedName: 'applicationId',
          type: {
            name: 'String'
          }
        },
        permissions: {
          required: false,
          serializedName: 'permissions',
          type: {
            name: 'Composite',
            className: 'Permissions'
          }
        }
      }
    }
  };
};

module.exports = AccessPolicyEntry;
