/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
// TODO: Include PageTemplateModels here too?? Probably
 */


/**
 * @class
 * Initializes a new instance of the Sku class.
 * @constructor
 * @member {string} [family] SKU family name
 * 
 * @member {string} [name] SKU name
 * 
 */
export interface Sku {
    family?: string;
    name?: string;
}

/**
 * @class
 * Initializes a new instance of the AccessPolicyEntry class.
 * @constructor
 * @member {uuid} [tenantId] Tenant ID of the principal
 * 
 * @member {uuid} [objectId] Object ID of the principal
 * 
 * @member {uuid} [applicationId]  Application ID of the client making request
 * on behalf of a principal
 * 
 * @member {object} [permissions] Permissions that the principal has for this
 * vault
 * 
 * @member {array} [permissions.keys] SKU family name
 * 
 * @member {array} [permissions.secrets] SKU name
 * 
 */
export interface AccessPolicyEntry {
    tenantId?: string;
    objectId?: string;
    applicationId?: string;
    permissions?: Permissions;
}

/**
 * @class
 * Initializes a new instance of the Permissions class.
 * @constructor
 * @member {array} [keys] SKU family name
 * 
 * @member {array} [secrets] SKU name
 * 
 */
export interface Permissions {
    keys?: string[];
    secrets?: string[];
}

/**
 * @class
 * Initializes a new instance of the VaultProperties class.
 * @constructor
 * Properties of the vault
 * @member {string} [vaultUri] URL of the vault
 * 
 * @member {uuid} [tenantId] Tenant ID
 * 
 * @member {object} [sku] SKU details
 * 
 * @member {string} [sku.family] SKU family name
 * 
 * @member {string} [sku.name] SKU name
 * 
 * @member {array} [accessPolicies] Access policies for one or more principals
 * 
 * @member {boolean} [enabledForDeployment] Enabled or disabled for deployment
 * 
 * @member {boolean} [enabledForDiskEncryption] Enabled or disabled for disk
 * encryption
 * 
 * @member {boolean} [enabledForTemplateDeployment] Enabled or disabled for
 * Azure Resource Manager template deployment
 * 
 */
export interface VaultProperties {
    vaultUri?: string;
    tenantId?: string;
    sku?: Sku;
    accessPolicies?: AccessPolicyEntry[];
    enabledForDeployment?: boolean;
    enabledForDiskEncryption?: boolean;
    enabledForTemplateDeployment?: boolean;
}

/**
 * @class
 * Initializes a new instance of the Resource class.
 * @constructor
 * @member {string} [id] Resource Id
 * 
 * @member {string} [name] Resource name
 * 
 * @member {string} [type] Resource type
 * 
 * @member {string} location Resource location
 * 
 * @member {object} [tags] Resource tags
 * 
 */
export interface Resource extends BaseResource {
    id?: string;
    name?: string;
    type?: string;
    location: string;
    tags?: { [propertyName: string]: string };
}

/**
 * @class
 * Initializes a new instance of the VaultCreateOrUpdateParameters class.
 * @constructor
 * Parameters to create or update a vault
 * @member {object} properties Gets or sets the properties of the vault.
 * 
 * @member {string} [properties.vaultUri] URL of the vault
 * 
 * @member {uuid} [properties.tenantId] Tenant ID
 * 
 * @member {object} [properties.sku] SKU details
 * 
 * @member {string} [properties.sku.family] SKU family name
 * 
 * @member {string} [properties.sku.name] SKU name
 * 
 * @member {array} [properties.accessPolicies] Access policies for one or more
 * principals
 * 
 * @member {boolean} [properties.enabledForDeployment] Enabled or disabled for
 * deployment
 * 
 * @member {boolean} [properties.enabledForDiskEncryption] Enabled or disabled
 * for disk encryption
 * 
 * @member {boolean} [properties.enabledForTemplateDeployment] Enabled or
 * disabled for Azure Resource Manager template deployment
 * 
 */
export interface VaultCreateOrUpdateParameters extends Resource {
    properties: VaultProperties;
}

/**
 * @class
 * Initializes a new instance of the Vault class.
 * @constructor
 * Resource information with extended details.
 * @member {object} [properties] Properties of the vault
 * 
 * @member {string} [properties.vaultUri] URL of the vault
 * 
 * @member {uuid} [properties.tenantId] Tenant ID
 * 
 * @member {object} [properties.sku] SKU details
 * 
 * @member {string} [properties.sku.family] SKU family name
 * 
 * @member {string} [properties.sku.name] SKU name
 * 
 * @member {array} [properties.accessPolicies] Access policies for one or more
 * principals
 * 
 * @member {boolean} [properties.enabledForDeployment] Enabled or disabled for
 * deployment
 * 
 * @member {boolean} [properties.enabledForDiskEncryption] Enabled or disabled
 * for disk encryption
 * 
 * @member {boolean} [properties.enabledForTemplateDeployment] Enabled or
 * disabled for Azure Resource Manager template deployment
 * 
 */
export interface Vault extends Resource {
    properties?: VaultProperties;
}

/**
 * @class
 * Initializes a new instance of the SubResource class.
 * @constructor
 * @member {string} [id] Resource Id
 * 
 */
export interface SubResource extends BaseResource {
    id?: string;
}
