/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

var models = require('./index');

var util = require('util');

/**
 * @class
 * Initializes a new instance of the VaultProperties class.
 * @constructor
 * Properties of the vault
 * @member {string} [vaultUri] URL of the vault
 * 
 * @member {uuid} [tenantId] Tenant ID
 * 
 * @member {object} [sku] SKU details
 * 
 * @member {string} [sku.family] SKU family name
 * 
 * @member {string} [sku.name] SKU name
 * 
 * @member {array} [accessPolicies] Access policies for one or more principals
 * 
 * @member {boolean} [enabledForDeployment] Enabled or disabled for deployment
 * 
 * @member {boolean} [enabledForDiskEncryption] Enabled or disabled for disk
 * encryption
 * 
 * @member {boolean} [enabledForTemplateDeployment] Enabled or disabled for
 * Azure Resource Manager template deployment
 * 
 */
function VaultProperties() {
}

/**
 * Defines the metadata of VaultProperties
 *
 * @returns {object} metadata of VaultProperties
 *
 */
VaultProperties.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'VaultProperties',
    type: {
      name: 'Composite',
      className: 'VaultProperties',
      modelProperties: {
        vaultUri: {
          required: false,
          serializedName: 'vaultUri',
          type: {
            name: 'String'
          }
        },
        tenantId: {
          required: false,
          serializedName: 'tenantId',
          type: {
            name: 'String'
          }
        },
        sku: {
          required: false,
          serializedName: 'sku',
          type: {
            name: 'Composite',
            className: 'Sku'
          }
        },
        accessPolicies: {
          required: false,
          serializedName: 'accessPolicies',
          type: {
            name: 'Sequence',
            element: {
                required: false,
                serializedName: 'AccessPolicyEntryElementType',
                type: {
                  name: 'Composite',
                  className: 'AccessPolicyEntry'
                }
            }
          }
        },
        enabledForDeployment: {
          required: false,
          serializedName: 'enabledForDeployment',
          type: {
            name: 'Boolean'
          }
        },
        enabledForDiskEncryption: {
          required: false,
          serializedName: 'enabledForDiskEncryption',
          type: {
            name: 'Boolean'
          }
        },
        enabledForTemplateDeployment: {
          required: false,
          serializedName: 'enabledForTemplateDeployment',
          type: {
            name: 'Boolean'
          }
        }
      }
    }
  };
};

module.exports = VaultProperties;
