/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

var models = require('./index');

var util = require('util');

/**
 * @class
 * Initializes a new instance of the Vault class.
 * @constructor
 * Resource information with extended details.
 * @member {object} [properties] Properties of the vault
 * 
 * @member {string} [properties.vaultUri] URL of the vault
 * 
 * @member {uuid} [properties.tenantId] Tenant ID
 * 
 * @member {object} [properties.sku] SKU details
 * 
 * @member {string} [properties.sku.family] SKU family name
 * 
 * @member {string} [properties.sku.name] SKU name
 * 
 * @member {array} [properties.accessPolicies] Access policies for one or more
 * principals
 * 
 * @member {boolean} [properties.enabledForDeployment] Enabled or disabled for
 * deployment
 * 
 * @member {boolean} [properties.enabledForDiskEncryption] Enabled or disabled
 * for disk encryption
 * 
 * @member {boolean} [properties.enabledForTemplateDeployment] Enabled or
 * disabled for Azure Resource Manager template deployment
 * 
 */
function Vault() {
  Vault['super_'].call(this);
}

util.inherits(Vault, models['Resource']);

/**
 * Defines the metadata of Vault
 *
 * @returns {object} metadata of Vault
 *
 */
Vault.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'Vault',
    type: {
      name: 'Composite',
      className: 'Vault',
      modelProperties: {
        id: {
          required: false,
          readOnly: true,
          serializedName: 'id',
          type: {
            name: 'String'
          }
        },
        name: {
          required: false,
          readOnly: true,
          serializedName: 'name',
          type: {
            name: 'String'
          }
        },
        type: {
          required: false,
          readOnly: true,
          serializedName: 'type',
          type: {
            name: 'String'
          }
        },
        location: {
          required: true,
          serializedName: 'location',
          type: {
            name: 'String'
          }
        },
        tags: {
          required: false,
          serializedName: 'tags',
          type: {
            name: 'Dictionary',
            value: {
                required: false,
                serializedName: 'StringElementType',
                type: {
                  name: 'String'
                }
            }
          }
        },
        properties: {
          required: false,
          serializedName: 'properties',
          type: {
            name: 'Composite',
            className: 'VaultProperties'
          }
        }
      }
    }
  };
};

module.exports = Vault;
