/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

import { ServiceClientOptions, RequestOptions, ServiceCallback } from 'ms-rest';
import * as models from '../models';


/**
 * @class
 * Vaults
 * __NOTE__: An instance of this class is automatically created for an
 * instance of the KeyVaultManagementClient.
 */
export interface Vaults {

    /**
     * Creates a new Azure key vault.
     *
     * @param {string} resourceGroupName The name of the Resource Group to which
     * the server belongs.
     * 
     * @param {string} vaultName Name of the vault
     * 
     * @param {object} parameters Parameters to create or update the vault
     * 
     * @param {object} [parameters.properties] Gets or sets the properties of the
     * vault.
     * 
     * @param {string} [parameters.properties.vaultUri] URL of the vault
     * 
     * @param {uuid} [parameters.properties.tenantId] Tenant ID
     * 
     * @param {object} [parameters.properties.sku] SKU details
     * 
     * @param {string} [parameters.properties.sku.family] SKU family name
     * 
     * @param {string} [parameters.properties.sku.name] SKU name
     * 
     * @param {array} [parameters.properties.accessPolicies] Access policies for
     * one or more principals
     * 
     * @param {boolean} [parameters.properties.enabledForDeployment] Enabled or
     * disabled for deployment
     * 
     * @param {boolean} [parameters.properties.enabledForDiskEncryption] Enabled
     * or disabled for disk encryption
     * 
     * @param {boolean} [parameters.properties.enabledForTemplateDeployment]
     * Enabled or disabled for Azure Resource Manager template deployment
     * 
     * @param {string} [parameters.location] Resource location
     * 
     * @param {object} [parameters.tags] Resource tags
     * 
     * @param {object} [options] Optional Parameters.
     * 
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     * 
     * @param {ServiceCallback} [callback] callback function; see ServiceCallback
     * doc in ms-rest index.d.ts for details
     */
    createOrUpdate(resourceGroupName: string, vaultName: string, parameters: models.VaultCreateOrUpdateParameters, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.Vault>): void;
    createOrUpdate(resourceGroupName: string, vaultName: string, parameters: models.VaultCreateOrUpdateParameters, callback: ServiceCallback<models.Vault>): void;

    /**
     * Deletes the specified Azure key vault.
     *
     * @param {string} resourceGroupName The name of the Resource Group to which
     * the vault belongs.
     * 
     * @param {string} vaultName The name of the vault to delete
     * 
     * @param {object} [options] Optional Parameters.
     * 
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     * 
     * @param {ServiceCallback} [callback] callback function; see ServiceCallback
     * doc in ms-rest index.d.ts for details
     */
    deleteMethod(resourceGroupName: string, vaultName: string, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.Vault>): void;
    deleteMethod(resourceGroupName: string, vaultName: string, callback: ServiceCallback<models.Vault>): void;

    /**
     * Gets the specified Azure key vault.
     *
     * @param {string} resourceGroupName The name of the Resource Group to which
     * the vault belongs.
     * 
     * @param {string} vaultName The name of the vault.
     * 
     * @param {object} [options] Optional Parameters.
     * 
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     * 
     * @param {ServiceCallback} [callback] callback function; see ServiceCallback
     * doc in ms-rest index.d.ts for details
     */
    get(resourceGroupName: string, vaultName: string, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.Vault>): void;
    get(resourceGroupName: string, vaultName: string, callback: ServiceCallback<models.Vault>): void;

    /**
     * The List operation gets information about the vaults associated with the
     * subscription and within the specified resource group.
     *
     * @param {string} resourceGroupName The name of the Resource Group to which
     * the vault belongs.
     * 
     * @param {number} top Maximum number of results to return.
     * 
     * @param {object} [options] Optional Parameters.
     * 
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     * 
     * @param {ServiceCallback} [callback] callback function; see ServiceCallback
     * doc in ms-rest index.d.ts for details
     */
    list(resourceGroupName: string, top: number, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.VaultListResult>): void;
    list(resourceGroupName: string, top: number, callback: ServiceCallback<models.VaultListResult>): void;

    /**
     * The List operation gets information about the vaults associated with the
     * subscription.
     *
     * @param {number} top Maximum number of results to return.
     * 
     * @param {object} [options] Optional Parameters.
     * 
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     * 
     * @param {ServiceCallback} [callback] callback function; see ServiceCallback
     * doc in ms-rest index.d.ts for details
     */
    listAll(top: number, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.VaultListResult>): void;
    listAll(top: number, callback: ServiceCallback<models.VaultListResult>): void;

    /**
     * The List operation gets information about the vaults associated with the
     * subscription and within the specified resource group.
     *
     * @param {string} nextPageLink The NextLink from the previous successful call
     * to List operation.
     * 
     * @param {object} [options] Optional Parameters.
     * 
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     * 
     * @param {ServiceCallback} [callback] callback function; see ServiceCallback
     * doc in ms-rest index.d.ts for details
     */
    listNext(nextPageLink: string, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.VaultListResult>): void;
    listNext(nextPageLink: string, callback: ServiceCallback<models.VaultListResult>): void;

    /**
     * The List operation gets information about the vaults associated with the
     * subscription.
     *
     * @param {string} nextPageLink The NextLink from the previous successful call
     * to List operation.
     * 
     * @param {object} [options] Optional Parameters.
     * 
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     * 
     * @param {ServiceCallback} [callback] callback function; see ServiceCallback
     * doc in ms-rest index.d.ts for details
     */
    listAllNext(nextPageLink: string, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.VaultListResult>): void;
    listAllNext(nextPageLink: string, callback: ServiceCallback<models.VaultListResult>): void;
}
